trainer: dist_forces

dataset:
  - src: /private/home/mshuaibi/baselines/data/data/ocp_s2ef/train/20M/
    normalize_labels: True
    target_mean: -0.7586356401443481
    target_std: 2.981738567352295
    grad_target_mean: 0.0
    grad_target_std: 2.981738567352295
  - src: /private/home/mshuaibi/baselines/data/data/ocp_s2ef/val/is_1M/

logger: tensorboard

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True
