includes:
- configs/ocp_s2ef/base.yml

model:
  name: dimenetplusplus
  hidden_channels: 64
  out_emb_channels: 128
  cutoff: 6.0
  num_radial: 3
  num_spherical: 4
  regress_forces: True
  use_pbc: True

optim:
  batch_size: 24
  eval_batch_size: 8
  num_workers: 64
  lr_initial: 0.001
  lr_gamma: 0.1
  lr_milestones: # epochs at which lr_initial <- lr_initial * lr_gamma
    - 15
    - 20
  warmup_epochs: 3
  warmup_factor: 0.2
  max_epochs: 50
  force_coefficient: 500
  num_gpus: 2
