includes:
- configs/ocp_s2ef/base_200k.yml
#- configs/ocp_s2ef/base_2M.yml
#- configs/ocp_s2ef/base_20M.yml
#- configs/ocp_s2ef/base_all.yml

model:
  name: cgcnn
  atom_embedding_size: 1024
  fc_feat_size: 256
  num_fc_layers: 3
  num_graph_conv_layers: 3

optim:
  batch_size: 256
  eval_batch_size: 128
  num_workers: 64
  lr_initial: 0.0001
  lr_gamma: 0.1
  lr_milestones: # epochs at which lr_initial <- lr_initial * lr_gamma
    - 5
    - 8
    - 10
  warmup_epochs: 3
  warmup_factor: 0.2
  max_epochs: 30
  force_coefficient: 100
  #eval_every: 50000
  num_gpus: 8
