includes:
- /private/home/mshuaibi/baselines/configs/ocp_s2ef/base_all.yml

model:
  name: schnet
  hidden_channels: 1024
  num_filters: 256
  num_interactions: 3
  num_gaussians: 200
  cutoff: 6.0
  use_pbc: True

optim:
  batch_size: 32
  eval_batch_size: 16
  num_workers: 64
  lr_initial: 0.0005
  lr_gamma: 0.1
  lr_milestones: # epochs at which lr_initial <- lr_initial * lr_gamma
    - 3
    - 5
    - 8
  warmup_epochs: 1
  warmup_factor: 0.2
  max_epochs: 30
  force_coefficient: 100
  eval_every: 10000
